# Generated by Django 6.0.5 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('insurance_provider', models.CharField(max_length=160)),
                ('policy_type', models.CharField(max_length=120)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('expiry_date', 'full_name'),
            },
        ),
    ]
