# Generated by Django 6.0.5 on 2026-05-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['advisor', 'expiry_date'], name='clients_cli_advisor_b226dc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['advisor', 'is_active'], name='clients_cli_advisor_641b40_idx'),
        ),
    ]
