# Generated by Django 6.0.5 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('language', models.CharField(choices=[('english', 'English'), ('yoruba', 'Yoruba'), ('hausa', 'Hausa'), ('igbo', 'Igbo')], max_length=20)),
                ('category', models.CharField(choices=[('insurance_basics', 'Insurance basics'), ('policy_explanations', 'Policy explanations'), ('claims_guidance', 'Claims guidance'), ('terminology', 'Insurance terminology')], max_length=40)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'language', 'title'),
                'indexes': [models.Index(fields=['language', 'category', 'is_published'], name='education_e_languag_789aeb_idx')],
            },
        ),
    ]
