# Generated by Django 6.0.5 on 2026-05-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['advisor', 'reminder_date', 'status'], name='reminders_r_advisor_b87a75_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('client', 'reminder_type'), name='unique_client_reminder_type'),
        ),
    ]
