# Generated by Django 6.0.5 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('client_created', 'Client created'), ('client_updated', 'Client updated'), ('client_deleted', 'Client deleted'), ('renewal_added', 'Renewal added'), ('reminder_triggered', 'Reminder triggered')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ('-created_at',),
            },
        ),
    ]
